FROM node:20-alpine AS builder
WORKDIR /app
COPY . .
RUN npm install
ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
RUN cd backoffice && npx vite build

FROM node:20-alpine
RUN npm install -g serve
COPY --from=builder /app/backoffice/dist /dist
EXPOSE 3000
CMD ["sh", "-c", "serve -s /dist -l ${PORT:-3000}"]
