FROM node:20-alpine AS builder
WORKDIR /app
COPY . .
RUN npm install
ARG VITE_SERVER_URL
ENV VITE_SERVER_URL=$VITE_SERVER_URL
WORKDIR /app/client
RUN npx vite build

FROM node:20-alpine
RUN npm install -g serve
COPY --from=builder /app/client/dist /dist
EXPOSE 3000
CMD ["sh", "-c", "serve -s /dist -l ${PORT:-3000}"]
